<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2026-07-10T10:30:04-07:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'America/Los_Angeles',
];
