<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2026-07-10T12:43:48-07:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.last_cleared
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.5.2',
    'version_db_installed' => '20260203004500',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1783704603,
    ],
    'email' => [
        'default' => [
            'address' => 'stev@mac.com',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
    'cache' => [
        'last_cleared' => 1783712628,
        'clear' => [
            'thumbnails' => false,
        ],
    ],
];
