<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2026-07-10T10:37:10-07:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.google_fonts.managed_families
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Git Repo',
            'google_fonts' => [
                'families' => '[{"family":"Prata","variants":["regular"]},{"family":"Source Sans 3","variants":["regular","italic"]}]',
                'display' => 'swap',
                'provider' => 'bunny',
                'typography_preset' => 'prata-source',
                'custom_overrides' => false,
                'override_theme_css' => false,
                'apply_theme_defaults' => false,
                'body_font' => 'Source Sans 3',
                'heading_font' => 'Prata',
                'body_font_weight' => '',
                'heading_font_weight' => '',
                'body_font_color' => '',
                'heading_font_color' => '',
                'heading_base_font_size' => '',
                'body_font_size' => '',
                'apply_header_footer' => false,
                'footer_nuclear_override' => false,
                'override_inline_fonts' => false,
                'host_locally' => true,
                'managed_families' => '["Prata","Source Sans 3"]',
            ],
            'editor' => [
                'ckeditor4' => [
                    'custom_config_options' => [
                        'font_names' => 'Arial/Arial, Helvetica, sans-serif;Comic Sans MS/Comic Sans MS, cursive;Courier New/Courier New, Courier, monospace;Georgia/Georgia, serif;Lucida Sans Unicode/Lucida Sans Unicode, Lucida Grande, sans-serif;Tahoma/Tahoma, Geneva, sans-serif;Times New Roman/Times New Roman, Times, serif;Trebuchet MS/Trebuchet MS, Helvetica, sans-serif;Verdana/Verdana, Geneva, sans-serif;Prata/"Prata", sans-serif;Source Sans 3/"Source Sans 3", sans-serif',
                    ],
                ],
            ],
        ],
    ],
];
